# Demo to how to lead another file in ansible

- name: Load another file
  hosts: all
  tasks:
    - name: Print hello world
      ansible.builtin.debug:
        msg: Hello World

    - name: Include task list in play
      ansible.builtin.include_tasks:
        file: universe.yml
